package cn.hylstudio.skykoma.plugin.idea.model.payload;

import cn.hylstudio.skykoma.plugin.idea.model.ProjectInfoDto;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class UploadProjectPayload {
    private String scanId;
    private ProjectInfoDto projectInfoDto;

    public UploadProjectPayload(ProjectInfoDto projectInfoDto) {
        // -------------- generated by skykoma begin --------------
        this.scanId = projectInfoDto.getScanId();
        this.projectInfoDto = projectInfoDto;

    }
}
