package cn.hylstudio.skykoma.plugin.idea;

import com.google.common.collect.Sets;

import java.util.Set;

public class SkykomaConstants {

    private SkykomaConstants() {

    }

    public static final String END_LINE = ";";
    public static final String OUTPUT_TEMPLATE = "" +
            "// -------------- generated by skykoma begin --------------\n" +
            "%s\n" +
            "// -------------- generated by skykoma end --------------";
    public static final String UNKNOWN_TYPE = "unknown";
    public static final String OBJECT_CLASS = "java.lang.Object";
    public static final String TYPE_TIMESTAMP = "java.sql.Timestamp";
    public static final String TYPE_LONG = "java.lang.Long";

    public static final String LOADING_CACHE_GET_METHOD = "com.google.common.cache.LoadingCache.get";
    public static final String LOADING_CACHE_GET_CLASS = "com.google.common.cache.LoadingCache";
    public static final String EVENT_BUS_PUBLISH_METHOD = "org.springframework.context.ApplicationEventPublisher.publishEvent";
    public static final String EVENT_BUS_CLASS = "org.springframework.context.ApplicationEventPublisher";
    public static final String EVENT_BUS_ONEVENT_METHOD = "org.springframework.context.ApplicationListener.onApplicationEvent";
    public static final String ANN_REQUEST_MAPPING_CLASS = "org.springframework.web.bind.annotation.RequestMapping";
    public static final String SERVICE_ANNOTATION_CLASS = "org.springframework.stereotype.Service";
    public static final String COMPONENT_ANNOTATION_CLASS = "org.springframework.stereotype.Component";
    public static final String CONTROLLER_ANNOTATION_CLASS = "org.springframework.stereotype.Controller";
    public static final String REST_CONTROLLER_ANNOTATION_CLASS = "org.springframework.web.bind.annotation.RestController";
    public static final String JPA_TABLE_CLASS = "javax.persistence.Table";
    public static final String JPA_COLUMN_CLASS = "javax.persistence.Column";
    public static final String JPA_ENTITY_ANNOTATION_CLASS = "javax.persistence.Entity";
    public static final Set<String> CONTROLLER_ANNOTATIONS = Sets.newHashSet(
            SkykomaConstants.CONTROLLER_ANNOTATION_CLASS,
            SkykomaConstants.REST_CONTROLLER_ANNOTATION_CLASS
    );

    public static final String NOTIFICATION_GROUP_ID_DEFAULT = "Skykoma Notification - default";
    public static final String NOTIFICATION_GROUP_KEY_DEFAULT = "skykoma.notifications.default";
    public static final String NOTIFICATION_GROUP_ID_ERROR = "Skykoma Notification - error";
    public static final String NOTIFICATION_GROUP_KEY_ERROR = "skykoma.notifications.error";
    public static final String PLUGIN_ID = "cn.hylstudio.skykoma.plugin.idea";
    public static final String PLUGIN_CONFIG_PREFIX = PLUGIN_ID + ".config.";
    public static final String DATA_SERVER_API_HOST = PLUGIN_CONFIG_PREFIX + "data_server_api_host";
    public static final String DATA_SERVER_API_KEY = PLUGIN_CONFIG_PREFIX + "data_server_api_key";
    public static final String DATA_SERVER_ENABLED = PLUGIN_CONFIG_PREFIX + "data_server_enabled";
    public static final Boolean DATA_SERVER_ENABLED_DEFAULT = Boolean.FALSE;
    public static final String AGENT_SERVER_LISTEN_ADDRESS = PLUGIN_CONFIG_PREFIX + "agent_server_listen_address";
    public static final String AGENT_SERVER_LISTEN_ADDRESS_DEFAULT = "http://127.0.0.1";
    public static final String AGENT_SERVER_LISTEN_PORT = PLUGIN_CONFIG_PREFIX + "agent_server_listen_port";
    public static final String JUPYTER_SERVER_HB_PORT = PLUGIN_CONFIG_PREFIX + "jupyter_server_hb_port";
    public static final String JUPYTER_SERVER_SHELL_PORT = PLUGIN_CONFIG_PREFIX + "jupyter_server_shell_port";
    public static final String JUPYTER_SERVER_IOPUB_PORT = PLUGIN_CONFIG_PREFIX + "jupyter_server_iopub_port";
    public static final String JUPYTER_SERVER_STDIN_PORT = PLUGIN_CONFIG_PREFIX + "jupyter_server_stdin_port";
    public static final String JUPYTER_SERVER_CONTROL_PORT = PLUGIN_CONFIG_PREFIX + "jupyter_server_control_port";
    public static final int AGENT_SERVER_LISTEN_PORT_DEFAULT = 2333;
    public static final int JUPYTER_SERVER_HB_PORT_DEFAULT = 2334;
    public static final int JUPYTER_SERVER_SHELL_PORT_DEFAULT = 2335;
    public static final int JUPYTER_SERVER_IOPUB_PORT_DEFAULT = 2336;
    public static final int JUPYTER_SERVER_STDIN_PORT_DEFAULT = 2337;
    public static final int JUPYTER_SERVER_CONTROL_PORT_DEFAULT = 2338;
    public static final String JUPYTER_PYTHON_EXECUTABLE = PLUGIN_CONFIG_PREFIX + "jupyter_python_executable";
    public static final String JUPYTER_PYTHON_EXECUTABLE_DEFAULT = "python";
    public static final String JUPYTER_KERNEL_NAME = PLUGIN_CONFIG_PREFIX + "jupyter_kernel_name";
    public static final String JUPYTER_KERNEL_NAME_PREFIX = "skykoma-agent-";
    public static final String JUPYTER_KERNEL_NAME_DEFAULT = "idea";
    
    public static final String GENERATE_CURRENT_METHOD_NAME_ENABLED = PLUGIN_CONFIG_PREFIX + "gen_current_method_name";
    public static final Boolean GENERATE_CURRENT_METHOD_NAME_ENABLED_DEFAULT = true;
    public static final String GENERATE_LOG_VARIABLE_NAME = PLUGIN_CONFIG_PREFIX + "gen_log_variable_name";
    public static final String GENERATE_LOG_VARIABLE_NAME_DEFAULT = "LOGGER";

}
