# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Auto Release

on:
  push:
    tags:
    - 'v*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Checkout barnch
      uses: actions/checkout@v4.1.1
    - name: Set up JDK 17
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.9.0
      with:
        gradle-version: '7.4.2'
        arguments: buildPlugin publishPlugin -PprojVersion=${{steps.get_version.outputs.VERSION}} -PpublishToken={{secrets.IDEA_PUBLISH_TOKEN}}
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{steps.get_version.outputs.VERSION}}
        files: build/distributions/skykoma-plugin-idea-${{steps.get_version.outputs.VERSION}}.zip
